site_name: SQLActive
site_url: https://daireto.github.io/sqlactive/
repo_name: daireto/sqlactive
repo_url: https://github.com/daireto/sqlactive/
theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
nav:
  - Home: INDEX.md
  - Docs:
    - ActiveRecord Mixin:
      - Overview: pages/active_record_mixin/OVERVIEW.md
      - API Reference: pages/active_record_mixin/API_REFERENCE.md
    - TImestamp Mixin: pages/TIMESTAMP_MIXIN.md
    - Serialization Mixin: pages/SERIALIZATION_MIXIN.md
    - Smart Queries Mixin: pages/SMART_QUERY_MIXIN.md
    - Inspection Mixin: pages/INSPECTION_MIXIN.md
  - Development:
    - Contributing: CONTRIBUTING.md
extra:
  version:
    provider: mike
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daireto/sqlactive/
      name: daireto/sqlactive
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sqlactive/
      name: 'PyPI: sqlactive'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mike
