site_name: SQLActive
site_url: https://daireto.github.io/sqlactive/
repo_name: daireto/sqlactive
repo_url: https://github.com/daireto/sqlactive/
theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
nav:
  - Home: index.md
  - Docs:
    - ActiveRecordMixin:
      - Overview: pages/active_record_mixin/overview.md
      - API Reference: pages/active_record_mixin/api_reference.md
    - TImestampMixin: pages/timestamp_mixin.md
    - SmartQueryMixin: pages/smart_query_mixin.md
    - InspectionMixin: pages/inspection_mixin.md
  - Development:
    - Contributing: contributing.md
extra:
  version:
    provider: mike
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daireto/sqlactive/
      name: daireto/sqlactive
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sqlactive/
      name: 'PyPI: sqlactive'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mike
