site_name: SQLActive
site_url: https://mydomain.org/
repo_name: daireto/sqlactive
repo_url: https://github.com/daireto/sqlactive
theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy
    - content.code.select
nav:
  - Home: index.md
  - Docs:
    - ActiveRecordMixin:
      - Overview: pages/active_record_mixin/overview.md
      - API Reference: pages/active_record_mixin/api_reference.md
    - TImestampMixin: pages/timestamp_mixin.md
    - SmartQueryMixin: pages/smart_query_mixin.md
    - InspectionMixin: pages/inspection_mixin.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
